- name: Key
  apt_key: id=7BD9BF62 url=http://nginx.org/keys/nginx_signing.key state=present

- name: Repo
  apt_repository: repo='deb [arch=amd64] http://nginx.org/packages/ubuntu/ {{codename}} nginx' state=present filename="nginx"
- name: Repo
  apt_repository: repo='deb-src [arch=amd64] http://nginx.org/packages/ubuntu/ {{codename}} nginx' state=present filename="nginx"

- name: apt-get install nginx
  apt: name=nginx update_cache=yes state=latest
  notify:
    - restart nginx
