- name: Repo
  deb822_repository:
    name: mono
    types: [deb]
    uris: "http://nginx.org/packages/ubuntu/"
    signed_by: "https://nginx.org/keys/nginx_signing.key"
    architectures: [amd64]
    suites: ["{{codename}}"]
    components: [nginx]
    enabled: yes

- name: Install
  apt: name=nginx