---

- name: setup workstation
  hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: no

  pre_tasks:
    - name: Get ubuntu release
      command: "sed 's/DISTRIB_CODENAME=//;t;d' /etc/upstream-release/lsb-release"
      register: get_ubuntu_release
      changed_when: False
    - name: Get ubuntu version
      command: "sed 's/DISTRIB_RELEASE=//;t;d' /etc/upstream-release/lsb-release"
      register: get_ubuntu_version
      changed_when: False
    - name: Get kernel version
      shell: uname -r
      register: get_kernel_version
      changed_when: False
    #- name: apt-get upgrade
    #  apt: upgrade=yes
    #  changed_when: False
    #- name: apt-get update
    #  apt: update_cache=yes
    #  changed_when: False
    - locale_gen: name=ru_RU.UTF-8 state=present
    - locale_gen: name=en_US.UTF-8 state=present

  vars:
    codename: "{{get_ubuntu_release.stdout}}"
    ubuntu_version: "{{get_ubuntu_version.stdout}}"
    kernel_version: "{{get_kernel_version.stdout}}"
    user_path: "~{{user}}"
    home_path: "{{user_path | expanduser}}"
    db_root_password: "{{lookup('env', 'DB_ROOT_PASSWORD')}}"

  vars_prompt:
    - name: user
      prompt: whoami?
      private: no

  tasks:
    - debug: msg="Ubuntu {{ubuntu_version}} {{codename}}"
    - debug: msg="Username {{user}}"
    - debug: msg="Home path {{home_path}}"
    - include: tasks/packages.yml

  roles:
    - { role: asdf }
    - { role: mono }
    - { role: clickhouse }
    - { role: chrome_driver }
    - { role: docker }
    - { role: doublecmd }
    - { role: git }
    - { role: google_chrome }
    - { role: grub }
    - { role: i386 }
    - { role: keepassxc }
    - { role: keyboard_shortcuts }
    - { role: nginx }
    - { role: ntp }
    - { role: opera }
    - { role: postgres }
    - { role: python }
    - { role: rbenv }
    - { role: redis }
    - { role: ruby }
    - { role: sublime_text }
    - { role: telegram }
    - { role: tor_browser }
    - { role: transmission }
    # - { role: virtualbox }
    - { role: wine }
    - { role: xfce_panel }
    - { role: yarn }
    - { role: zoom }
    - { role: skype }
