---
# https://yandex.com/support/disk/cli-clients.xml#cli-install
- name: Key
  apt_key: url="http://repo.yandex.ru/yandex-disk/YANDEX-DISK-KEY.GPG"

- name: Repo
  # apt: deb=https://repo.yandex.ru/yandex-disk/yandex-disk_latest_amd64.deb
  apt_repository: repo='deb http://repo.yandex.ru/yandex-disk/deb/ stable main'

- name: apt-get install yandex-disk
  apt: name=yandex-disk update_cache=yes state=latest

- name: config
  template:
    src: config.cfg.j2
    dest: "~{{user}}/.config/yandex-disk/config.cfg"
    backup: true
  become: true
  become_user: "{{user}}"

# https://github.com/slytomcat/yandex-disk-indicator
- name: Yandex Disk Indicator - add ppa
  apt_repository: repo="ppa:slytomcat/ppa" codename="{{codename}}" filename=yd-tools

- name: install Yandex Disk Indicator
  apt: name=yd-tools update_cache=yes
