- name: snap install
  shell: snap install telegram-desktop
  changed_when: false

- name: Autostart
  template:
    src: telegram.desktop.j2
    dest: "~{{user}}/.config/autostart/telegram.desktop"
  become: true
  become_user: "{{user}}"    

- name: Add quick launch icon
  include_role: name="shared/quick_launch"
  vars:
    config: "~{{user}}/.config/autostart/telegram.desktop"
    binary: telegram
