- name: install
  community.general.flatpak:
    name: org.telegram.desktop

-
  include_role: name="shared/autostart"
  vars:
    src: /var/lib/flatpak/exports/share/applications/org.telegram.desktop.desktop
    name: telegram.desktop

-
  include_role: name="shared/quick_launch"
  vars:
    config: /var/lib/flatpak/exports/share/applications/org.telegram.desktop.desktop
    binary: telegram
