- name: install
  apt: 
    name: telegram-desktop

# - name: 
#   include_role: name="shared/autostart"
#   vars:
#     config: telegram.desktop

- name: 
  include_role: name="shared/quick_launch"
  vars:
    config: /usr/share/applications/telegramdesktop.desktop
    binary: telegram
