# https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk?utm_source=chrome-ntp-icon

- name: Repo
  apt_repository: repo="ppa:phoerious/keepassxc" state=present filename="keepassxc" codename={{codename}}

- name: apt-get install keepassxc
  apt: name=keepassxc update_cache=yes state=latest

- name: set autostart
  copy:
    dest: "~{{user}}/.config/autostart/keepass.desktop"
    src: "../templates/keepass.desktop"
    owner: "{{user}}"
    group: "{{user}}"

- name: Add quick launch icon
  include_role: name="shared/quick_launch"
  vars:
    config: "~{{user}}/.config/autostart/keepass.desktop"
    binary: keepass
