- name: Uninstall software
  apt: name="{{item}}" purge=yes force=yes state=absent
  with_items:
    - thunderbird
    - libreoffice-draw
    - libreoffice-impress
    - libreoffice-math
    - unity-lens-photos
    - empathy
    - gnome-mahjongg
    - gnomine
    - gnome-sudoku
    - aisleriot
    - totem-common
    - unity-webapps-common
    - ibus-pinyin
    - bittorrent
    - evolution-data-server-online-accounts
    - landscape-client-ui-install
    - vlc
    - redshift
    - tomboy
    - xplayer
    - xed
    - hexchat
    - rhythmbox

- name: Clean
  apt: autoremove=yes

- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - htop
    - mc
    - apt-transport-https
    - gitg
    - rsync
    - vim
    - lsb-core
    - build-essential
    - libssl-dev
    - openssl
    - curl
    - imagemagick
    - libmagic-dev
    - nautilus-dropbox
    - p7zip-full
    - httpie
    - mpv
    - smartmontools
    - apache2-utils
    - traceroute
    - tcptraceroute
