- name: Uninstall software
  apt: 
    pkg: ['thunderbird', 'libreoffice-draw', 'libreoffice-impress', 'libreoffice-math', 'unity-lens-photos', 'empathy', 'gnome-mahjongg', 'gnomine', 'gnome-sudoku', 'aisleriot', 'totem-common', 'unity-webapps-common', 'ibus-pinyin', 'bittorrent', 'evolution-data-server-online-accounts', 'landscape-client-ui-install', 'vlc', 'redshift', 'tomboy', 'xplayer', 'xed', 'hexchat', 'rhythmbox']
    purge: yes 
    force: yes 
    state: absent

- name: Clean
  apt: autoremove=yes

- name: Install packages
  apt: 
    pkg: ['htop', 'iotop', 'mc', 'apt-transport-https', 'gitg', 'rsync', 'vim', 'lsb-core', 'build-essential', 'libssl-dev', 'openssl', 'curl', 'imagemagick', 'libmagic-dev', 'p7zip-full', 'httpie', 'mpv', 'smartmontools', 'apache2-utils', 'traceroute', 'tcptraceroute', 'bluez', 'blueman', 'cifs-utils', 'smbclient', 'gdebi-core', 'mtp-tools']
    state: latest
  