- name: install
  community.general.flatpak:
    name: org.keepassxc.KeePassXC

-
  include_role: name="shared/autostart"
  vars:
    src: /var/lib/flatpak/exports/share/applications/org.keepassxc.KeePassXC.desktop
    name: keepassxc.desktop

-
  include_role: name="shared/quick_launch"
  vars:
    config: /var/lib/flatpak/exports/share/applications/org.keepassxc.KeePassXC.desktop
    binary: keepassxc
