- name: git clone
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "~{{user}}/.asdf"
  become: true
  become_user: "{{user}}"

- name: autostart
  copy:
    src: ../templates/asdf.sh
    dest: "~{{user}}/.bashrc"
    mode: 0644
    owner: "{{user}}"
