- name: Repo
  deb822_repository:
    name: tor
    types: [deb]
    uris: "https://deb.torproject.org/torproject.org"
    signed_by: "https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc"
    architectures: [amd64]
    suites: ["{{codename}}"]
    components: [main]
    enabled: yes

- name: Install
  apt: 
    name: ["tor", "deb.torproject.org-keyring", "torbrowser-launcher"]

- name: 
  include_role: name="shared/quick_launch"
  vars:
    config: "/usr/share/applications/torbrowser.desktop"
    binary: torbrowser
