- name: Key
  apt_key: 
    keyserver: keyserver.ubuntu.com
    id: F1656F24C74CD1D8

- name: Repo
  apt_repository: repo="deb [arch=amd64] http://mirror.truenetwork.ru/mariadb/repo/10.3/ubuntu {{codename}} main" filename="mariadb-10"
- name: Repo src
  apt_repository: repo="deb-src http://mirror.truenetwork.ru/mariadb/repo/10.3/ubuntu {{codename}} main" filename="mariadb-10"

- name: Install packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - mariadb-client
    - mariadb-server
    - libmariadb-dev
    - libmariadb-dev-compat
    - libmariadbclient18
  register: mysql_installed

- name: Install mysql-python
  pip: name=mysql-python state=latest

- name: Enable socket login
  ini_file: 
    path: "/etc/mysql/mariadb.conf.d/50-server.cnf"
    section: "mysqld"
    state: present
    option: "plugin-load-add"
    value: "auth_socket.so"
  register: socket_login_enabled

- name: restart mysql
  systemd: name=mariadb state=restarted
  when: socket_login_enabled.changed

- name: Set root Password
  mysql_user: name=root host={{ item }} password={{ root_password }} state=present
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
  when: mysql_installed.changed

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}" --password={{root_password}}'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
  when: mysql_installed.changed

- name: Setup roles
  command: 'mysql -ne "{{ item }}" --password={{root_password}}'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False
  when: mysql_installed.changed

#- name:  Allow root login with password
#  command: >
#    mysql --user=root mysql --batch --skip-column-names  --execute="update user set plugin='' where User='root'"
#  changed_when: False

- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}" --password={{root_password}}'
  with_items:
    - DROP DATABASE test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False
  ignore_errors: True
  when: mysql_installed.changed

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}" --password={{root_password}}'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
  when: mysql_installed.changed