- name: apt-get install teamviewer
  apt: deb=https://download.teamviewer.com/download/linux/teamviewer_amd64.deb

# # http://askubuntu.com/questions/419605/teamviewer-9-ubuntu-13-10-sound
# - name: Run teamviewer winecfg
#   command: teamviewer --winecfg
#   become: yes
#   become_user: "{{ username }}"
#   become_method: su 