- name: Repo
  deb822_repository:
    name: opera
    types: [deb]
    uris: "https://deb.opera.com/opera-stable/"
    signed_by: "https://deb.opera.com/archive.key"
    architectures: [amd64]
    suites: [stable]
    components: [non-free]

- name: Install
  apt: name=opera-stable
