- name: Key
  apt_key: url=https://deb.opera.com/archive.key state=present

- name: Repo
  apt_repository: repo="deb https://deb.opera.com/opera-stable/ stable non-free" state=present filename="opera"

- name: apt-get install opera-stable
  apt: name=opera update_cache=yes install_recommends=no state=latest
