- name: Deps
  apt:
    name: ["gvfs", "gvfs-backends", "gvfs-fuse"]
  
- name: Repo
  deb822_repository:
    name: "doublecmd"
    types: [deb]
    uris: "https://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_{{ubuntu_version}}/"
    signed_by: "https://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_{{ubuntu_version}}/Release.key"
    architectures: [amd64]
    suites: ["/"]
    components: []

- name: Install
  apt: name=doublecmd-gtk

- name: 
  include_role: name="shared/quick_launch"
  vars:
    config: /usr/share/applications/doublecmd.desktop
    binary: doublecmd
