- name: Key
  apt_key: url="http://download.opensuse.org/repositories/home:Alexx2000/xUbuntu_{{ubuntu_version}}/Release.key"

- name: Repo
  apt_repository: repo="deb http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_{{ubuntu_version}}/ /" filename=doublecmd

- name: apt-get install doublecmd-gtk
  apt: name=doublecmd-gtk state=latest update_cache=true

- name: Add quick launch icon
  include_role: name="shared/quick_launch"
  vars:
    config: doublecmd.desktop
    binary: doublecmd
