- name: ask email
  pause:
    prompt: "GIT email"
  register: git_ask_email
  changed_when: false

- name: ask name
  pause:
    prompt: "GIT name"
  register: git_ask_name
  changed_when: false

- name: Install
  apt: name=git

- name: Configure
  shell: git config --global {{item.field}} "{{item.value}}"
  become: true
  become_user: "{{user}}"
  changed_when: false
  register: result
  with_items:
    - item:
      field: user.name
      value: "{{git_ask_name.user_input}}"
    - item:
      field: user.email
      value: "{{git_ask_email.user_input}}"
