- name: Drop OpenJDK
  apt: name="openjdk*" state="absent" purge=true

- name: Repo
  apt_repository: 
    repo: ppa:webupd8team/java
    codename: "{{codename}}"
    filename: java
#- name: Repo src
#  apt_repository: repo='deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu {{get_ubuntu_release.stdout}} main' state=present filename=java

# - name: Accept Java 8 License
#   become: yes
#   debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install packages
  apt: name={{item}} update_cache=yes state=latest
  with_items:
    - default-jre
    - default-jdk
#    - oracle-java8-installer
#    - ca-certificates
#    - oracle-java8-set-default
#  notify:
#    - reload env

- name: Java version
  command: "java --version"
  register: get_java_version
  changed_when: False

- name: Java container version
  command: "javac --version"
  register: get_javac_version
  changed_when: False

- debug: msg="JAVA {{get_java_version.stdout}} {{get_javac_version.stdout}}"