- name: Repo
  deb822_repository:
    name: sublime-text
    types: [deb]
    uris: "https://download.sublimetext.com/"
    signed_by: "https://download.sublimetext.com/sublimehq-pub.gpg"
    architectures: [amd64]
    suites: [apt/stable/]
    components: []
    enabled: yes

- name:
  apt: name=sublime-text

- name: Add default editor
  lineinfile: 
    path: "~{{user}}/.bashrc"
    regexp: "{{item}}=.*"
    line: "export {{item}}=\"subl -w\""
  with_items:
    - "EDITOR"
    - "VISUAL"
    - "BUNDLER_EDITOR"

- name: 
  include_role: name="shared/quick_launch"
  vars:
    config: "/usr/share/applications/sublime_text.desktop"
    binary: sublime_text
