- name: apt intsall yarn
  deb822_repository:
    name: yarn
    types: [deb]
    uris: "https://dl.yarnpkg.com/debian/"
    signed_by: "https://dl.yarnpkg.com/debian/pubkey.gpg"
    architectures: [amd64]
    suites: [stable]
    components: [main]
    enabled: yes
