# https://github.com/jdauphant/ansible-role-packaging/blob/master/tasks/Debian.yml
# https://wiki.winehq.org/Ubuntu

- name: Uninstall
  apt:
    pkg: "winetricks"
    purge: yes
    force: yes
    state: absent

- name: Deps
  apt:
    pkg: ["cabextract", "aria2", "binutils", "fuseiso", "p7zip-full", "pkexec", "tor", "unrar", "unzip", "xdg-utils", "xz-utils", "zenity"]
    state: "latest"

- name: Repo
  deb822_repository:
    name: "wine"
    types: [deb]
    uris: "https://dl.winehq.org/wine-builds/ubuntu"
    signed_by: "https://dl.winehq.org/wine-builds/winehq.key"
    architectures: ["amd64", "i386"]
    suites: ["{{codename}}"]
    components: [main]

- name: Install
  apt: name=winehq-stable install_recommends=yes

- name: winetrics
  get_url:
    url: "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks"
    dest: "/usr/local/bin/winetricks"
    mode: 0755

- name: .wine dir
  file:
    path: "~{{user}}/.wine"
    state: directory
  become: yes
  become_user: "{{user}}"

- name: winetrics completions
  get_url:
    url: "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks.bash-completion"
    dest: "~{{user}}/.wine/winetricks.bash-completion"
  become: yes
  become_user: "{{user}}"

- name: configure winetricks completions
  copy:
    src: ../templates/winetricks.sh
    dest: /etc/profile.d/winetricks.sh
    owner: root
    mode: 0755
