- name: Repo
  deb822_repository:
    name: mono
    types: [deb]
    uris: "https://download.mono-project.com/repo/ubuntu"
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
    architectures: [amd64]
    suites: ["stable-{{codename}}"]
    components: [main]
    enabled: yes

- name: Install
  apt: name=mono-complete