- name: Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: Repo
  apt_repository: repo='deb https://download.mono-project.com/repo/ubuntu stable-{{codename}} main' state=present filename="mono"

- name: Install
  apt: name="mono-complete" update_cache=yes state=latest
