- name: apt-get install numlockx
  apt: name="numlockx" state=latest

- name: Enable autologin
  ini_file: 
    path: "/etc/lightdm/lightdm.conf"
    section: "Seat:*"
    state: present
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - item:
      option: "autologin-user"
      value: "{{user}}"
    - item:
      option: "autologin-user-timeout"
      value: 0

- name: Enable Numlock during startup
  ini_file: 
    path: "/etc/lightdm/lightdm.conf.d/00-keyboard.conf"
    section: "SeatDefaults"
    state: present
    option: "greeter-setup-script"
    value: "/usr/bin/numlockx on"
