- name: Deps
  apt:
    name: ["ca-certificates", "curl", "gnupg"]

- name: Repo
  deb822_repository:
    name: "docker"
    types: [deb]
    uris: "https://download.docker.com/linux/ubuntu"
    signed_by: "https://download.docker.com/linux/ubuntu/gpg"
    architectures: [amd64]
    suites: [nodistro]
    components: [main]

- name: Install
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-buildx-plugin", "docker-compose-plugin"]
