- name: Deps
  apt:
    name: ["apt-transport-https", "ca-certificates", "curl", "software-properties-common"]
    state: present
    update_cache: yes

- name: Key
  apt_key: url="https://download.docker.com/linux/ubuntu/gpg"

- name: Repo
  apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu {{codename}} stable" filename="docker"

- name: apt-get install docker-ce
  apt: name="docker-ce" state=latest update_cache=yes