- name: Repo
  deb822_repository:
    name: postgresql
    types: [deb]
    uris: "https://apt.postgresql.org/pub/repos/apt"
    signed_by: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    architectures: [amd64]
    suites: ["{{codename}}-pgdg"]
    components: [main]
    enabled: yes

- name: Install
  apt: 
    name: ["postgresql-client-15", "libpq-dev"]