- name: Repo
  deb822_repository:
    name: "google-chrome"
    types: [deb]
    uris: "https://dl.google.com/linux/chrome/deb/"
    signed_by: "https://dl.google.com/linux/linux_signing_key.pub"
    architectures: [amd64]
    suites: [stable]
    components: [main]

- name: Install
  apt: name=google-chrome-stable

- name: 
  include_role: name="shared/quick_launch"
  vars:
    config: "/usr/share/applications/google-chrome.desktop"
    binary: google-chrome
